controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

show_all_recipes:
    path: /recette
    controller: App\Controller\RecetteController::show

show_recipes_by_id:
    path: /recette/{id}
    controller: App\Controller\RecetteController::showById

create_recipe:
    path: /api/createrecette
    controller: App\Controller\RecetteController::createRecette

modify_recipe:
    path: /api/modifyrecette
    controller: App\Controller\RecetteController::modifyRecette

delete_recipe:
    path: /api/deleterecette
    controller: App\Controller\RecetteController::deleteRecette

register_user:
    path: /register
    controller: App\Controller\RegistrationController::registerUser

delete_user:
    path: /deleteuser
    controller: App\Controller\RegistrationController::deleteUser

api_login:
    path: /api/login